-- Migration: make dsemcq_question_options.label nullable
-- New questions generated by agent-v2 will not have a label (A/B/C/D).
-- Old questions keep their label values for backward compatibility.
-- The app assigns display labels (A/B/C/D) at runtime from option array index.

ALTER TABLE dsemcq_question_options
  ALTER COLUMN label DROP NOT NULL;
